---
title: "The Data Science of Marketing With R - Predict wit R"
author: "Fabio Araujo"
date: "6 de abril de 2018"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Connect to our data
```{r}
myPredictData <- read.csv("D:/00 - Fabio/Ex_Files_Data_Science_of_Marketing/Exercise_Files/04_02/prediction-r.csv")
```

# Sum our classification to see it 
```{r}
table(myPredictData$sales.classification)
```

# Output column names to easy reference
```{r}
names(myPredictData)
```

# Install the algorithm package
```{r}
install.packages("tree")
```

# Bring our newly installed algorithm into our library of packages
```{r}
library(tree)
```

# Configure our algorithm to create our tree
```{r}
myDecisionTree <- tree(sales.classification ~ capita + drive.by.traffic + complimentary.establishments + competition + weather + unemployment.rate + var1 + var2 + var3, data=myPredictData)
```

# Plot our tree  so we can see  the algorithms output
```{r}
plot(myDecisionTree)
```

# Label our tree
```{r}
text(myDecisionTree)
```

# Prune our tree
```{r}
myPrunedTree <- prune.tree(myDecisionTree,best = 3)
```

# Plot our pruned tree
```{r}
plot(myPrunedTree)
```

# Text our pruned tree
```{r}
text(myPrunedTree)
```







