---
title: "The Data Science of Marketing - Cojoint"
author: "Fabio Araujo"
date: "7 de abril de 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Connect to our data 
```{r}
myConjointData <- read.csv("D:/00 - Fabio/Ex_Files_Data_Science_of_Marketing/Exercise_Files/06_02/conjoint-r.csv")
myConjointDataProfilesMatrix <- read.csv("D:/00 - Fabio/Ex_Files_Data_Science_of_Marketing/Exercise_Files/06_02/conjoint-r-profiles-matrix.csv")
myConjointDataLevelNames <- read.csv("D:/00 - Fabio/Ex_Files_Data_Science_of_Marketing/Exercise_Files/06_02/conjoint-r-level-names.csv")
```

# Step 1.) Install the conjoint package
```{r}
install.packages("conjoint")
```

# install.packages("conjoint")
```{r}
library(conjoint)
```

# Step 2.) Load the conjoint package
```{r}
library(conjoint)
```

# Step 3 if needed.) If R throws an error, refer to the readme file in the Exercise_Files
```{r}
```

# Model some of our data
```{r}
caUtilities(y=myConjointData[1,], x=myConjointDataProfilesMatrix, z=myConjointDataLevelNames)

myConjointData[1,]
```
# Model all of our data
```{r}
caUtilities(y=myConjointData, x=myConjointDataProfilesMatrix, z=myConjointDataLevelNames)

```